apiVersion: v1
kind: service
metadata: 
  name: redis
  labels: redis-service
  app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app