apiVersion: v1
kind: service
metadata: 
  name: result-service
  labels: result-service
  app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app